//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IQuoteService")]
    public interface IQuoteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuoteService/GetQuote", ReplyAction="http://tempuri.org/IQuoteService/GetQuoteResponse")]
        string GetQuote();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuoteService/GetQuote", ReplyAction="http://tempuri.org/IQuoteService/GetQuoteResponse")]
        System.Threading.Tasks.Task<string> GetQuoteAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQuoteServiceChannel : UI.ServiceReference1.IQuoteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuoteServiceClient : System.ServiceModel.ClientBase<UI.ServiceReference1.IQuoteService>, UI.ServiceReference1.IQuoteService {
        
        public QuoteServiceClient() {
        }
        
        public QuoteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuoteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuoteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuoteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetQuote() {
            return base.Channel.GetQuote();
        }
        
        public System.Threading.Tasks.Task<string> GetQuoteAsync() {
            return base.Channel.GetQuoteAsync();
        }
    }
}
